### ISSUE TITLE
About RDP Algorithm

### ISSUE THREAD

**Issue by aleynakutuk6** [leosampaio/sketchformer#5]
I couldn't find in the code whether you have called RDP Algorithm or not. I found that you used RDP Algorithm in read_svg function, but you never call that function during training / evaluation phases. In the original paper, it says the following:

"Following Eck et al. [12] we simplify all sketches using the RDP algorithm [10] and normalize stroke length."

Could you please clarify on that issue?

**Comment by leosampaio** [comment]
Hi!

We have the code but ended up not using it in our framework. We found it easier to download the pre-RDPed sketches directly from the Quick! Draw GitHub page: https://github.com/googlecreativelab/quickdraw-dataset#sketch-rnn-quickdraw-dataset

As the page describes, those sketches were already "processed with RDP line simplification with an epsilon parameter of 2.0. Each category will be stored in its own .npz file, for example, cat.npz.". And these are the same pre-processed sketches used on SketchRNN (Eck et al. [12]).
